from pydantic import JsonValue

from .model import Twin

def observed_budgets(twin: Twin) -> list[dict[str, JsonValue]]: ...

class Coach:
    def __init__(self, twin: Twin) -> None: ...
    def review(self, request: dict[str, JsonValue]) -> dict[str, JsonValue]: ...
