// GENERATED by scripts/sync-tokens.cjs from design/tokens.json — 직접 수정하지 말고 `pnpm tokens:sync`를 실행한다.
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  // .dark:root 변수 블록이 content 스캔에서 제거되지 않도록 유지
  safelist: ["dark"],
  theme: {
    colors: {
      "transparent": "transparent",
      "current": "currentColor",
      "background": "rgb(var(--color-background) / <alpha-value>)",
      "foreground": "rgb(var(--color-foreground) / <alpha-value>)",
      "card": "rgb(var(--color-card) / <alpha-value>)",
      "card-foreground": "rgb(var(--color-card-foreground) / <alpha-value>)",
      "popover": "rgb(var(--color-popover) / <alpha-value>)",
      "popover-foreground": "rgb(var(--color-popover-foreground) / <alpha-value>)",
      "primary": "rgb(var(--color-primary) / <alpha-value>)",
      "primary-foreground": "rgb(var(--color-primary-foreground) / <alpha-value>)",
      "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
      "secondary-foreground": "rgb(var(--color-secondary-foreground) / <alpha-value>)",
      "muted": "rgb(var(--color-muted) / <alpha-value>)",
      "muted-foreground": "rgb(var(--color-muted-foreground) / <alpha-value>)",
      "accent": "rgb(var(--color-accent) / <alpha-value>)",
      "accent-foreground": "rgb(var(--color-accent-foreground) / <alpha-value>)",
      "destructive": "rgb(var(--color-destructive) / <alpha-value>)",
      "destructive-foreground": "rgb(var(--color-destructive-foreground) / <alpha-value>)",
      "destructive-muted": "rgb(var(--color-destructive-muted) / <alpha-value>)",
      "positive": "rgb(var(--color-positive) / <alpha-value>)",
      "positive-foreground": "rgb(var(--color-positive-foreground) / <alpha-value>)",
      "positive-muted": "rgb(var(--color-positive-muted) / <alpha-value>)",
      "warning": "rgb(var(--color-warning) / <alpha-value>)",
      "warning-foreground": "rgb(var(--color-warning-foreground) / <alpha-value>)",
      "warning-muted": "rgb(var(--color-warning-muted) / <alpha-value>)",
      "info": "rgb(var(--color-info) / <alpha-value>)",
      "info-foreground": "rgb(var(--color-info-foreground) / <alpha-value>)",
      "info-muted": "rgb(var(--color-info-muted) / <alpha-value>)",
      "highlight": "rgb(var(--color-highlight) / <alpha-value>)",
      "highlight-foreground": "rgb(var(--color-highlight-foreground) / <alpha-value>)",
      "inverse": "rgb(var(--color-inverse) / <alpha-value>)",
      "inverse-foreground": "rgb(var(--color-inverse-foreground) / <alpha-value>)",
      "border": "rgb(var(--color-border) / <alpha-value>)",
      "input": "rgb(var(--color-input) / <alpha-value>)",
      "ring": "rgb(var(--color-ring) / <alpha-value>)",
      "env-dining": "rgb(var(--color-env-dining) / <alpha-value>)",
      "env-dining-muted": "rgb(var(--color-env-dining-muted) / <alpha-value>)",
      "env-transport": "rgb(var(--color-env-transport) / <alpha-value>)",
      "env-transport-muted": "rgb(var(--color-env-transport-muted) / <alpha-value>)",
      "env-health": "rgb(var(--color-env-health) / <alpha-value>)",
      "env-health-muted": "rgb(var(--color-env-health-muted) / <alpha-value>)",
      "env-leisure": "rgb(var(--color-env-leisure) / <alpha-value>)",
      "env-leisure-muted": "rgb(var(--color-env-leisure-muted) / <alpha-value>)",
      "env-shopping": "rgb(var(--color-env-shopping) / <alpha-value>)",
      "env-shopping-muted": "rgb(var(--color-env-shopping-muted) / <alpha-value>)",
      "env-grocery": "rgb(var(--color-env-grocery) / <alpha-value>)",
      "env-grocery-muted": "rgb(var(--color-env-grocery-muted) / <alpha-value>)",
      "env-etc": "rgb(var(--color-env-etc) / <alpha-value>)",
      "env-etc-muted": "rgb(var(--color-env-etc-muted) / <alpha-value>)",
      "white": "rgb(var(--color-white) / <alpha-value>)",
      "black": "rgb(var(--color-black) / <alpha-value>)"
    },
    borderRadius: {
      "none": "0px",
      "sm": "6px",
      "md": "10px",
      "lg": "15px",
      "xl": "20px",
      "2xl": "24px",
      "3xl": "32px",
      "full": "9999px"
    },
    extend: {
      fontFamily: {
        sans: ["Pretendard"],
      },
      fontSize: {
        "display": [
          "32px",
          {
            "lineHeight": "40px",
            "letterSpacing": "-0.5px",
            "fontWeight": "700"
          }
        ],
        "amount-lg": [
          "36px",
          {
            "lineHeight": "44px",
            "letterSpacing": "-0.5px",
            "fontWeight": "700"
          }
        ],
        "amount-md": [
          "24px",
          {
            "lineHeight": "32px",
            "letterSpacing": "-0.3px",
            "fontWeight": "600"
          }
        ],
        "amount-sm": [
          "16px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "h1": [
          "24px",
          {
            "lineHeight": "28px",
            "letterSpacing": "-0.3px",
            "fontWeight": "600"
          }
        ],
        "h2": [
          "20px",
          {
            "lineHeight": "28px",
            "letterSpacing": "-0.3px",
            "fontWeight": "600"
          }
        ],
        "h3": [
          "16px",
          {
            "lineHeight": "24px",
            "letterSpacing": "-0.2px",
            "fontWeight": "600"
          }
        ],
        "body-lg": [
          "18px",
          {
            "lineHeight": "28px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "body": [
          "16px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "body-sm": [
          "15px",
          {
            "lineHeight": "22px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "label": [
          "15px",
          {
            "lineHeight": "22px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ],
        "caption": [
          "13px",
          {
            "lineHeight": "18px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ],
        "button": [
          "16px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ]
      },
      height: {
        "touch": "44px",
        "button-lg": "56px",
        "button-md": "44px",
        "input": "44px",
        "icon": "24px",
        "icon-sm": "20px",
        "icon-lg": "28px",
        "icon-tile": "40px",
        "avatar": "50px"
      },
      minHeight: {
        "touch": "44px",
        "button-lg": "56px",
        "button-md": "44px",
        "input": "44px",
        "icon": "24px",
        "icon-sm": "20px",
        "icon-lg": "28px",
        "icon-tile": "40px",
        "avatar": "50px"
      },
      minWidth: {
        "touch": "44px",
        "button-lg": "56px",
        "button-md": "44px",
        "input": "44px",
        "icon": "24px",
        "icon-sm": "20px",
        "icon-lg": "28px",
        "icon-tile": "40px",
        "avatar": "50px"
      },
      width: {
        "touch": "44px",
        "button-lg": "56px",
        "button-md": "44px",
        "input": "44px",
        "icon": "24px",
        "icon-sm": "20px",
        "icon-lg": "28px",
        "icon-tile": "40px",
        "avatar": "50px"
      },
      transitionDuration: {
        "fast": "150ms",
        "base": "220ms",
        "slow": "320ms"
      },
    },
  },
  plugins: [],
};
