#!/usr/bin/env node
/**
 * design/tokens.json → tailwind.config.js, global.css, lib/theme.ts 생성
 *
 *   node scripts/sync-tokens.cjs          생성
 *   node scripts/sync-tokens.cjs --check  생성 결과가 현재 파일과 같은지만 확인 (CI용, 다르면 exit 1)
 *
 * 규칙:
 * - 시맨틱 색상(shadcn/React Native Reusables 규약)만 Tailwind 테마에 노출한다. 프리미티브 팔레트는 className에서 쓸 수 없다.
 *   예외: white, black (모드 무관 고정값, RNR 컴포넌트가 사용).
 * - 색상은 CSS 변수로 내보내 라이트/다크가 className 하나로 전환되게 한다 (darkMode: "class" + NativeWind colorScheme).
 * - Tailwind 기본 크기 스케일(text-sm, h-10, px-4 …)은 유지하고 타이포·크기 토큰은 extend로 추가한다.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const TOKENS_PATH = path.join(ROOT, "design", "tokens.json");
const CHECK = process.argv.includes("--check");

const tokens = JSON.parse(fs.readFileSync(TOKENS_PATH, "utf8"));
const MODES = tokens.$modes ?? ["light", "dark"];

// ---------- 참조 해석 ----------
function getByPath(obj, dotted) {
  return dotted.split(".").reduce((acc, key) => (acc == null ? undefined : acc[key]), obj);
}

function resolve(value, depth = 0) {
  if (depth > 10) throw new Error(`토큰 참조가 너무 깊습니다: ${JSON.stringify(value)}`);
  if (typeof value === "string") {
    const m = value.match(/^\{(.+)\}$/);
    if (!m) return value;
    const target = getByPath(tokens, m[1]);
    if (target === undefined) throw new Error(`참조를 찾을 수 없습니다: ${value}`);
    return resolve(target.$value !== undefined ? target.$value : target, depth + 1);
  }
  if (Array.isArray(value)) return value.map((v) => resolve(v, depth + 1));
  if (value && typeof value === "object") {
    const out = {};
    for (const [k, v] of Object.entries(value)) out[k] = resolve(v, depth + 1);
    return out;
  }
  return value;
}

function isTokenNode(node) {
  return node && typeof node === "object" && "$value" in node;
}

function walk(group, prefix, visit) {
  for (const [key, node] of Object.entries(group)) {
    if (key.startsWith("$")) continue;
    if (isTokenNode(node)) visit([...prefix, key], node);
    else if (node && typeof node === "object") walk(node, [...prefix, key], visit);
  }
}

// ---------- 색상 ----------
function hexToChannels(hex) {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  const n = parseInt(full.slice(0, 6), 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
}

const colors = []; // { name, values: { light, dark }, isHex }
walk(tokens.semantic.color, [], (parts, node) => {
  const raw = resolve(node.$value);
  const values = {};
  for (const mode of MODES) {
    const v = typeof raw === "object" ? raw[mode] : raw;
    if (v === undefined) throw new Error(`색상 토큰 ${parts.join(".")}에 ${mode} 값이 없습니다`);
    values[mode] = v;
  }
  const isHex = MODES.every((m) => /^#[0-9a-fA-F]{6}$/.test(values[m]));
  colors.push({ name: parts.join("-"), values, isHex, description: node.$description });
});

for (const fixed of ["white", "black"]) {
  const v = resolve(tokens.primitive.color[fixed].$value);
  const values = {};
  for (const mode of MODES) values[mode] = v;
  colors.push({ name: fixed, values, isHex: true, description: "모드 무관 고정값" });
}

const dupes = colors.map((c) => c.name).filter((n, i, a) => a.indexOf(n) !== i);
if (dupes.length) throw new Error(`시맨틱 색상 이름 충돌: ${dupes.join(", ")}`);

// ---------- 타이포그래피 ----------
const typography = {};
walk(tokens.semantic.typography, [], (parts, node) => {
  typography[parts.join("-")] = resolve(node.$value);
});

// ---------- 치수 ----------
function collectDimensions(group) {
  const out = {};
  walk(group, [], (parts, node) => {
    out[parts.join("-")] = resolve(node.$value);
  });
  return out;
}
const radius = collectDimensions(tokens.semantic.radius);
const size = collectDimensions(tokens.semantic.size);
const motion = collectDimensions(tokens.semantic.motion);
const fontFamily = resolve(tokens.primitive.fontFamily.sans.$value);

// ---------- 출력: tailwind.config.js ----------
const HEADER_JS = `// GENERATED by scripts/sync-tokens.cjs from design/tokens.json — 직접 수정하지 말고 \`pnpm tokens:sync\`를 실행한다.\n`;

const twColors = {
  transparent: "transparent",
  current: "currentColor",
};
for (const c of colors) {
  twColors[c.name] = c.isHex ? `rgb(var(--color-${c.name}) / <alpha-value>)` : `var(--color-${c.name})`;
}

const twFontSize = {};
for (const [name, t] of Object.entries(typography)) {
  twFontSize[name] = [
    `${t.fontSize}px`,
    { lineHeight: `${t.lineHeight}px`, letterSpacing: `${t.letterSpacing}px`, fontWeight: String(t.fontWeight) },
  ];
}

const twRadius = { none: "0px" };
for (const [k, v] of Object.entries(radius)) twRadius[k] = `${v}px`;

const twSize = {};
for (const [k, v] of Object.entries(size)) twSize[k] = `${v}px`;

const twDuration = {};
for (const [k, v] of Object.entries(motion)) twDuration[k.replace(/^duration-/, "")] = `${v}ms`;

const fmt = (obj, indent) => JSON.stringify(obj, null, 2).replace(/\n/g, "\n" + " ".repeat(indent));

const tailwindConfig =
  HEADER_JS +
  `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  // .dark:root 변수 블록이 content 스캔에서 제거되지 않도록 유지
  safelist: ["dark"],
  theme: {
    colors: ${fmt(twColors, 4)},
    borderRadius: ${fmt(twRadius, 4)},
    extend: {
      fontFamily: {
        sans: [${JSON.stringify(fontFamily)}],
      },
      fontSize: ${fmt(twFontSize, 6)},
      height: ${fmt(twSize, 6)},
      minHeight: ${fmt(twSize, 6)},
      minWidth: ${fmt(twSize, 6)},
      width: ${fmt(twSize, 6)},
      transitionDuration: ${fmt(twDuration, 6)},
    },
  },
  plugins: [],
};
`;

// ---------- 출력: global.css ----------
function cssVars(mode, indent) {
  const pad = " ".repeat(indent);
  return colors
    .map((c) => `${pad}--color-${c.name}: ${c.isHex ? hexToChannels(c.values[mode]) : c.values[mode]};`)
    .join("\n");
}
const globalCss = `/* GENERATED by scripts/sync-tokens.cjs from design/tokens.json — 직접 수정하지 말고 \`pnpm tokens:sync\`를 실행한다. */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
${cssVars("light", 4)}
  }

  .dark:root {
${cssVars("dark", 4)}
  }
}
`;

// ---------- 출력: lib/theme.ts ----------
function tsObject(obj, indent = 2) {
  const pad = " ".repeat(indent);
  const entries = Object.entries(obj).map(([k, v]) => {
    const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
    const val = v && typeof v === "object" && !Array.isArray(v) ? tsObject(v, indent + 2) : JSON.stringify(v);
    return `${pad}${key}: ${val},`;
  });
  return `{\n${entries.join("\n")}\n${" ".repeat(indent - 2)}}`;
}

const colorsByMode = {};
for (const mode of MODES) {
  colorsByMode[mode] = {};
  for (const c of colors) colorsByMode[mode][c.name] = c.values[mode];
}

const typographyStyles = {};
for (const [name, t] of Object.entries(typography)) {
  typographyStyles[name] = {
    fontFamily,
    fontSize: t.fontSize,
    lineHeight: t.lineHeight,
    fontWeight: String(t.fontWeight),
    letterSpacing: t.letterSpacing,
    ...(t.tabular ? { fontVariant: ["tabular-nums"] } : {}),
  };
}

const themeTs = `// GENERATED by scripts/sync-tokens.cjs from design/tokens.json — 직접 수정하지 말고 \`pnpm tokens:sync\`를 실행한다.
// className으로 표현할 수 없는 곳(StatusBar, 내비게이션 테마, 차트, Reanimated 보간)에서만 사용한다.
import type { TextStyle } from "react-native";

export const colors = ${tsObject(colorsByMode)} as const;

export type ColorScheme = keyof typeof colors;
export type ColorToken = keyof (typeof colors)["light"];

export function getColors(scheme: ColorScheme | null | undefined) {
  return colors[scheme === "dark" ? "dark" : "light"];
}

/** 폰트 패밀리. app.json의 expo-font 플러그인으로 등록되며 fontWeight로 굵기 파일이 선택된다. */
export const fontFamily = ${JSON.stringify(fontFamily)};

export const typography = ${tsObject(typographyStyles)} satisfies Record<string, TextStyle>;

export type TypographyToken = keyof typeof typography;

export const radius = ${tsObject(radius)} as const;

export const size = ${tsObject(size)} as const;

export const motion = ${tsObject(motion)} as const;
`;

// ---------- 쓰기 / 검사 ----------
const outputs = [
  ["tailwind.config.js", tailwindConfig],
  ["global.css", globalCss],
  ["lib/theme.ts", themeTs],
];

let stale = [];
for (const [rel, content] of outputs) {
  const abs = path.join(ROOT, rel);
  const current = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
  if (CHECK) {
    if (current !== content) stale.push(rel);
  } else {
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
    console.log(`생성: ${rel}`);
  }
}

if (CHECK) {
  if (stale.length) {
    console.error(`토큰 산출물이 최신이 아닙니다. \`pnpm tokens:sync\`를 실행하세요:\n  ${stale.join("\n  ")}`);
    process.exit(1);
  }
  console.log("토큰 산출물 최신 상태 확인");
} else {
  console.log(`색상 ${colors.length}개, 타이포 ${Object.keys(typography).length}개, 반경 ${Object.keys(radius).length}개`);
}
