// Generated by scripts/assets/build-furniture-sprites.ps1. Do not edit.
// contentRect is the original PNG canvas inside the expanded transparent PNG.
import type { FurnitureSpriteGeometry } from './sprite-geometry';

export const FURNITURE_GEOMETRY = {
  bed_black: {
    left: { pixelSize: { width: 807, height: 652 }, contentRect: { x: 38, y: 1, width: 732, height: 602 } },
    right: { pixelSize: { width: 807, height: 652 }, contentRect: { x: 38, y: 1, width: 732, height: 602 } },
    shop: { pixelSize: { width: 286, height: 231 }, contentRect: { x: 15, y: 2, width: 256, height: 210 } },
  },
  bed_original: {
    left: { pixelSize: { width: 807, height: 652 }, contentRect: { x: 38, y: 1, width: 732, height: 602 } },
    right: { pixelSize: { width: 807, height: 652 }, contentRect: { x: 38, y: 1, width: 732, height: 602 } },
    shop: { pixelSize: { width: 286, height: 231 }, contentRect: { x: 15, y: 2, width: 256, height: 210 } },
  },
  bed_pink: {
    left: { pixelSize: { width: 807, height: 652 }, contentRect: { x: 38, y: 1, width: 732, height: 602 } },
    right: { pixelSize: { width: 807, height: 652 }, contentRect: { x: 38, y: 1, width: 732, height: 602 } },
    shop: { pixelSize: { width: 286, height: 231 }, contentRect: { x: 15, y: 2, width: 256, height: 210 } },
  },
  bed_sunset: {
    left: { pixelSize: { width: 807, height: 652 }, contentRect: { x: 38, y: 1, width: 732, height: 602 } },
    right: { pixelSize: { width: 807, height: 652 }, contentRect: { x: 38, y: 1, width: 732, height: 602 } },
    shop: { pixelSize: { width: 286, height: 231 }, contentRect: { x: 15, y: 2, width: 256, height: 210 } },
  },
  bookcase_black: {
    left: { pixelSize: { width: 320, height: 539 }, contentRect: { x: 34, y: 1, width: 251, height: 507 } },
    right: { pixelSize: { width: 321, height: 539 }, contentRect: { x: 35, y: 1, width: 251, height: 507 } },
    shop: { pixelSize: { width: 164, height: 276 }, contentRect: { x: 19, y: 2, width: 126, height: 256 } },
  },
  bookcase_original: {
    left: { pixelSize: { width: 320, height: 539 }, contentRect: { x: 34, y: 1, width: 251, height: 507 } },
    right: { pixelSize: { width: 321, height: 539 }, contentRect: { x: 35, y: 1, width: 251, height: 507 } },
    shop: { pixelSize: { width: 164, height: 276 }, contentRect: { x: 19, y: 2, width: 126, height: 256 } },
  },
  bookcase_pink: {
    left: { pixelSize: { width: 320, height: 539 }, contentRect: { x: 34, y: 1, width: 251, height: 507 } },
    right: { pixelSize: { width: 321, height: 539 }, contentRect: { x: 35, y: 1, width: 251, height: 507 } },
    shop: { pixelSize: { width: 164, height: 276 }, contentRect: { x: 19, y: 2, width: 126, height: 256 } },
  },
  bookcase_sunset: {
    left: { pixelSize: { width: 320, height: 539 }, contentRect: { x: 34, y: 1, width: 251, height: 507 } },
    right: { pixelSize: { width: 321, height: 539 }, contentRect: { x: 35, y: 1, width: 251, height: 507 } },
    shop: { pixelSize: { width: 164, height: 276 }, contentRect: { x: 19, y: 2, width: 126, height: 256 } },
  },
  coffee_table_black: {
    left: { pixelSize: { width: 434, height: 289 }, contentRect: { x: 60, y: 1, width: 315, height: 243 } },
    right: { pixelSize: { width: 433, height: 289 }, contentRect: { x: 59, y: 1, width: 315, height: 243 } },
    shop: { pixelSize: { width: 356, height: 238 }, contentRect: { x: 50, y: 2, width: 256, height: 197 } },
  },
  coffee_table_original: {
    left: { pixelSize: { width: 434, height: 289 }, contentRect: { x: 60, y: 1, width: 315, height: 243 } },
    right: { pixelSize: { width: 433, height: 289 }, contentRect: { x: 59, y: 1, width: 315, height: 243 } },
    shop: { pixelSize: { width: 356, height: 238 }, contentRect: { x: 50, y: 2, width: 256, height: 197 } },
  },
  coffee_table_pink: {
    left: { pixelSize: { width: 434, height: 289 }, contentRect: { x: 60, y: 1, width: 315, height: 243 } },
    right: { pixelSize: { width: 433, height: 289 }, contentRect: { x: 59, y: 1, width: 315, height: 243 } },
    shop: { pixelSize: { width: 356, height: 238 }, contentRect: { x: 50, y: 2, width: 256, height: 197 } },
  },
  coffee_table_sunset: {
    left: { pixelSize: { width: 434, height: 289 }, contentRect: { x: 60, y: 1, width: 315, height: 243 } },
    right: { pixelSize: { width: 433, height: 289 }, contentRect: { x: 59, y: 1, width: 315, height: 243 } },
    shop: { pixelSize: { width: 356, height: 238 }, contentRect: { x: 50, y: 2, width: 256, height: 197 } },
  },
  desk_black: {
    left: { pixelSize: { width: 458, height: 415 }, contentRect: { x: 1, y: 1, width: 456, height: 403 } },
    right: { pixelSize: { width: 458, height: 415 }, contentRect: { x: 1, y: 1, width: 456, height: 403 } },
    shop: { pixelSize: { width: 260, height: 236 }, contentRect: { x: 2, y: 2, width: 256, height: 226 } },
  },
  desk_original: {
    left: { pixelSize: { width: 458, height: 415 }, contentRect: { x: 1, y: 1, width: 456, height: 403 } },
    right: { pixelSize: { width: 458, height: 415 }, contentRect: { x: 1, y: 1, width: 456, height: 403 } },
    shop: { pixelSize: { width: 260, height: 236 }, contentRect: { x: 2, y: 2, width: 256, height: 226 } },
  },
  desk_pink: {
    left: { pixelSize: { width: 458, height: 415 }, contentRect: { x: 1, y: 1, width: 456, height: 403 } },
    right: { pixelSize: { width: 458, height: 415 }, contentRect: { x: 1, y: 1, width: 456, height: 403 } },
    shop: { pixelSize: { width: 260, height: 236 }, contentRect: { x: 2, y: 2, width: 256, height: 226 } },
  },
  desk_sunset: {
    left: { pixelSize: { width: 458, height: 415 }, contentRect: { x: 1, y: 1, width: 456, height: 403 } },
    right: { pixelSize: { width: 458, height: 415 }, contentRect: { x: 1, y: 1, width: 456, height: 403 } },
    shop: { pixelSize: { width: 260, height: 236 }, contentRect: { x: 2, y: 2, width: 256, height: 226 } },
  },
  dining_chair_black: {
    left: { pixelSize: { width: 249, height: 346 }, contentRect: { x: 4, y: 1, width: 232, height: 335 } },
    right: { pixelSize: { width: 249, height: 346 }, contentRect: { x: 13, y: 1, width: 232, height: 335 } },
    shop: { pixelSize: { width: 192, height: 267 }, contentRect: { x: 5, y: 2, width: 176, height: 256 } },
  },
  dining_chair_original: {
    left: { pixelSize: { width: 249, height: 346 }, contentRect: { x: 4, y: 1, width: 232, height: 335 } },
    right: { pixelSize: { width: 249, height: 346 }, contentRect: { x: 13, y: 1, width: 232, height: 335 } },
    shop: { pixelSize: { width: 192, height: 267 }, contentRect: { x: 5, y: 2, width: 176, height: 256 } },
  },
  dining_chair_pink: {
    left: { pixelSize: { width: 249, height: 346 }, contentRect: { x: 4, y: 1, width: 232, height: 335 } },
    right: { pixelSize: { width: 249, height: 346 }, contentRect: { x: 13, y: 1, width: 232, height: 335 } },
    shop: { pixelSize: { width: 192, height: 267 }, contentRect: { x: 5, y: 2, width: 176, height: 256 } },
  },
  dining_chair_sunset: {
    left: { pixelSize: { width: 249, height: 346 }, contentRect: { x: 4, y: 1, width: 232, height: 335 } },
    right: { pixelSize: { width: 249, height: 346 }, contentRect: { x: 13, y: 1, width: 232, height: 335 } },
    shop: { pixelSize: { width: 192, height: 267 }, contentRect: { x: 5, y: 2, width: 176, height: 256 } },
  },
  dining_table_black: {
    left: { pixelSize: { width: 438, height: 402 }, contentRect: { x: 1, y: 1, width: 436, height: 390 } },
    right: { pixelSize: { width: 438, height: 402 }, contentRect: { x: 1, y: 1, width: 436, height: 390 } },
    shop: { pixelSize: { width: 260, height: 239 }, contentRect: { x: 2, y: 2, width: 256, height: 229 } },
  },
  dining_table_original: {
    left: { pixelSize: { width: 438, height: 402 }, contentRect: { x: 1, y: 1, width: 436, height: 390 } },
    right: { pixelSize: { width: 438, height: 402 }, contentRect: { x: 1, y: 1, width: 436, height: 390 } },
    shop: { pixelSize: { width: 260, height: 239 }, contentRect: { x: 2, y: 2, width: 256, height: 229 } },
  },
  dining_table_pink: {
    left: { pixelSize: { width: 438, height: 402 }, contentRect: { x: 1, y: 1, width: 436, height: 390 } },
    right: { pixelSize: { width: 438, height: 402 }, contentRect: { x: 1, y: 1, width: 436, height: 390 } },
    shop: { pixelSize: { width: 260, height: 239 }, contentRect: { x: 2, y: 2, width: 256, height: 229 } },
  },
  dining_table_sunset: {
    left: { pixelSize: { width: 438, height: 402 }, contentRect: { x: 1, y: 1, width: 436, height: 390 } },
    right: { pixelSize: { width: 438, height: 402 }, contentRect: { x: 1, y: 1, width: 436, height: 390 } },
    shop: { pixelSize: { width: 260, height: 239 }, contentRect: { x: 2, y: 2, width: 256, height: 229 } },
  },
  nightstand_black: {
    left: { pixelSize: { width: 244, height: 231 }, contentRect: { x: 30, y: 1, width: 185, height: 203 } },
    right: { pixelSize: { width: 243, height: 231 }, contentRect: { x: 29, y: 1, width: 185, height: 203 } },
    shop: { pixelSize: { width: 311, height: 294 }, contentRect: { x: 39, y: 3, width: 233, height: 256 } },
  },
  nightstand_original: {
    left: { pixelSize: { width: 244, height: 231 }, contentRect: { x: 30, y: 1, width: 185, height: 203 } },
    right: { pixelSize: { width: 243, height: 231 }, contentRect: { x: 29, y: 1, width: 185, height: 203 } },
    shop: { pixelSize: { width: 311, height: 294 }, contentRect: { x: 39, y: 3, width: 233, height: 256 } },
  },
  nightstand_pink: {
    left: { pixelSize: { width: 244, height: 231 }, contentRect: { x: 30, y: 1, width: 185, height: 203 } },
    right: { pixelSize: { width: 243, height: 231 }, contentRect: { x: 29, y: 1, width: 185, height: 203 } },
    shop: { pixelSize: { width: 311, height: 294 }, contentRect: { x: 39, y: 3, width: 233, height: 256 } },
  },
  nightstand_sunset: {
    left: { pixelSize: { width: 244, height: 231 }, contentRect: { x: 30, y: 1, width: 185, height: 203 } },
    right: { pixelSize: { width: 243, height: 231 }, contentRect: { x: 29, y: 1, width: 185, height: 203 } },
    shop: { pixelSize: { width: 311, height: 294 }, contentRect: { x: 39, y: 3, width: 233, height: 256 } },
  },
  sofa_black: {
    left: { pixelSize: { width: 616, height: 511 }, contentRect: { x: 34, y: 1, width: 553, height: 471 } },
    right: { pixelSize: { width: 617, height: 511 }, contentRect: { x: 29, y: 1, width: 553, height: 471 } },
    shop: { pixelSize: { width: 288, height: 241 }, contentRect: { x: 17, y: 3, width: 256, height: 218 } },
  },
  sofa_original: {
    left: { pixelSize: { width: 616, height: 511 }, contentRect: { x: 34, y: 1, width: 553, height: 471 } },
    right: { pixelSize: { width: 617, height: 511 }, contentRect: { x: 29, y: 1, width: 553, height: 471 } },
    shop: { pixelSize: { width: 288, height: 241 }, contentRect: { x: 17, y: 3, width: 256, height: 218 } },
  },
  sofa_pink: {
    left: { pixelSize: { width: 616, height: 511 }, contentRect: { x: 34, y: 1, width: 553, height: 471 } },
    right: { pixelSize: { width: 617, height: 511 }, contentRect: { x: 29, y: 1, width: 553, height: 471 } },
    shop: { pixelSize: { width: 288, height: 241 }, contentRect: { x: 17, y: 3, width: 256, height: 218 } },
  },
  sofa_sunset: {
    left: { pixelSize: { width: 616, height: 511 }, contentRect: { x: 34, y: 1, width: 553, height: 471 } },
    right: { pixelSize: { width: 617, height: 511 }, contentRect: { x: 29, y: 1, width: 553, height: 471 } },
    shop: { pixelSize: { width: 288, height: 241 }, contentRect: { x: 17, y: 3, width: 256, height: 218 } },
  },
  tv_set_black: {
    left: { pixelSize: { width: 468, height: 519 }, contentRect: { x: 30, y: 1, width: 408, height: 485 } },
    right: { pixelSize: { width: 467, height: 519 }, contentRect: { x: 29, y: 1, width: 409, height: 485 } },
    shop: { pixelSize: { width: 250, height: 278 }, contentRect: { x: 17, y: 3, width: 215, height: 256 } },
  },
  tv_set_original: {
    left: { pixelSize: { width: 468, height: 519 }, contentRect: { x: 30, y: 1, width: 408, height: 485 } },
    right: { pixelSize: { width: 467, height: 519 }, contentRect: { x: 29, y: 1, width: 409, height: 485 } },
    shop: { pixelSize: { width: 250, height: 278 }, contentRect: { x: 17, y: 3, width: 215, height: 256 } },
  },
  tv_set_pink: {
    left: { pixelSize: { width: 468, height: 519 }, contentRect: { x: 30, y: 1, width: 408, height: 485 } },
    right: { pixelSize: { width: 467, height: 519 }, contentRect: { x: 29, y: 1, width: 409, height: 485 } },
    shop: { pixelSize: { width: 250, height: 278 }, contentRect: { x: 17, y: 3, width: 215, height: 256 } },
  },
  tv_set_sunset: {
    left: { pixelSize: { width: 468, height: 519 }, contentRect: { x: 30, y: 1, width: 408, height: 485 } },
    right: { pixelSize: { width: 467, height: 519 }, contentRect: { x: 29, y: 1, width: 409, height: 485 } },
    shop: { pixelSize: { width: 250, height: 278 }, contentRect: { x: 17, y: 3, width: 215, height: 256 } },
  },
} satisfies Record<string, FurnitureSpriteGeometry>;
